# Generated by Django 5.1.4 on 2025-01-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='highlightdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainimage')),
                ('image_title', models.CharField(max_length=50)),
                ('image_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_offer_image', models.ImageField(upload_to='offerimage')),
                ('special_offer_title', models.CharField(max_length=50)),
                ('special_offer_description', models.CharField(max_length=200)),
            ],
        ),
    ]
