# Generated by Django 5.1.4 on 2025-01-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
