# Generated by Django 5.1.4 on 2025-01-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rateing',
            field=models.FloatField(default=2),
        ),
    ]
