# Generated by Django 5.1.4 on 2025-01-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_alter_product_rateing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_price',
            field=models.BigIntegerField(default=10000),
        ),
    ]
