# Generated by Django 5.1.4 on 2025-01-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
