# Generated by Django 5.1.4 on 2025-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
