# Generated by Django 5.1.4 on 2025-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_register_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_company',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='company'),
        ),
    ]
