# Generated by Django 5.1.4 on 2025-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_alter_register_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_company',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
