# Generated by Django 5.1.4 on 2025-01-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='eapp.product'),
        ),
    ]
