# Generated by Django 5.1.4 on 2025-01-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_alter_reviews_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewc', to='eapp.product'),
        ),
    ]
